### PR TITLE
Add metrics package to toolbox

### LINKED ISSUE #16: Move metrics to toolbox?
Do you guys think it makes sense to move the metics functionality in deepcell-tf to the toolbox?

I want to import it for our analysis pipeline, and the toolbox is much more lightweight than deepcell itself. 

If there's a particular reason this wouldn't be a good idea I can obviously just import deepcell instead. Not sure exactly what the scope of the toolbox is going to be.

### PR DESCRIPTION
**Pull request by ngreenwald**
Move the metrics package from deepcell-tf to toolbox

Closes #16

### CODE REVIEW

**Comment by ngreenwald** [comment]
It looks like tempfile.TemporaryDirectory doesn't work in Python 2.7; any suggestions for what to replace it with?

**Comment by ngreenwald** [comment]
Hey guys, I ported over the metrics package to the toolbox. I replaced all the test functions that used TF.test with pytest or np.test. However, the temp_dir package I use (tempfile) doesn't appear to have a temporarydirectory function in 2.7

**Comment by msschwartz21** [comment]
Could this suggestion from [stackoverflow post](https://stackoverflow.com/questions/19296146/tempfile-temporarydirectory-context-manager-in-python-2-7) help?

Another option is the "backports.tempfile" package on pypi: https://pypi.python.org/pypi/backports.tempfile

Quoting the project's description: "This package provides backports of new features in Python’s tempfile module under the backports namespace."

Install with:
`pip install backports.tempfile`

Then use it in your script:

```from backports import tempfile
with tempfile.TemporaryDirectory() as temp_dir:
    # modify files in this dir
# here the temporary directory does not exist any more.```

**Comment by ngreenwald** [comment]
Hey @msschwartz21, do you have any idea why metrics is failing on python 2.7 for one of the accuracy tests? It has failed every time I've pushed a commit, and only ever in the 2.7 build. However, it didn't do this in the deepcell-tf repo, which also tests against 2.7.

**Comment by willgraf** [comment]
The failure in question `test_save_error_ids`:

```
>           assert set(label_dict['correct']['y_true']) == y_true_correct
E           assert set([1, 2, 3]) == set([1, 3])
E             Extra items in the left set:
E             2
E             Full diff:
E             - set([1, 2, 3])
E             ?         ---
E             + set([1, 3])
```

**Comment by ngreenwald** [comment]
Hmmm, that could be it. I'm going to hard code in specific values for the random tests to try and track down what's going on

**Comment by ngreenwald** [comment]
@willgraf I switched from logger.warning to warnings.warn because pytest can check for warnings.warn. Do you know if there's a way for it check for logging as well? Or is this fine

**Comment by willgraf** [comment]
I am not sure how we can test log outputs. I think what you have is fine.

**Pull request merged**
